package com.eclinic.domain;
// Generated Jul 7, 2016 1:08:16 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "doctor", catalog = "eclinic")
public class Doctor implements Serializable {

	private long id;
	private String name;
	private String speciality;
	private Set<PatientVisit> patientVisits = new HashSet<PatientVisit>(0);

	public Doctor() {
	}

	public Doctor(String name, String specialiity) {
		this.name = name;
		this.speciality = specialiity;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "speciality")
	public String getSpeciality() {
		return this.speciality;
	}

	public void setSpeciality(String speciality) {
		this.speciality = speciality;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<PatientVisit> getPatientVisits() {
		return this.patientVisits;
	}

	public void setPatientVisits(Set<PatientVisit> patientVisits) {
		this.patientVisits = patientVisits;
	}

	@Override
	public String toString() {
		return "Doctor [id=" + id + ", name=" + name + ", speciality=" + speciality + ", patientVisits=" + patientVisits
				+ "]";
	}

}
