package com.eclinic.domain;
// Generated Jul 7, 2016 1:08:16 PM by Hibernate Tools 4.3.1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientDisease generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "patient_disease", catalog = "eclinic")
public class PatientDisease implements Serializable {

	private long id;
	private Disease disease;
	private Patient patient;
	private PatientVisit patientVisit;

	public PatientDisease() {
	}

	public PatientDisease(Disease disease, Patient patient, PatientVisit patientVisit) {
		this.disease = disease;
		this.patient = patient;
		this.patientVisit = patientVisit;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disease_id", nullable = false)
	public Disease getDisease() {
		return this.disease;
	}

	public void setDisease(Disease disease) {
		this.disease = disease;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_visit_id", nullable = false)
	public PatientVisit getPatientVisit() {
		return this.patientVisit;
	}

	public void setPatientVisit(PatientVisit patientVisit) {
		this.patientVisit = patientVisit;
	}

	@Override
	public String toString() {
		return "PatientDisease [id=" + id + ", disease=" + disease + ", patient=" + patient + ", patientVisit="
				+ patientVisit + "]";
	}

}
