package com.eclinic.domain;
// Generated Jul 7, 2016 1:08:16 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Prescription generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "prescription", catalog = "eclinic")
public class Prescription implements Serializable {

	private long id;
	private PatientVisit patientVisit;
	private Set<PrescriptionDrug> prescriptionDrugs = new HashSet<PrescriptionDrug>(0);

	public Prescription() {
	}

	public Prescription(PatientVisit patientVisit, Set<PrescriptionDrug> prescriptionDrugs) {
		this.patientVisit = patientVisit;
		this.prescriptionDrugs = prescriptionDrugs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_visit_id", nullable = false)
	public PatientVisit getPatientVisit() {
		return this.patientVisit;
	}

	public void setPatientVisit(PatientVisit patientVisit) {
		this.patientVisit = patientVisit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prescription")
	public Set<PrescriptionDrug> getPrescriptionDrugs() {
		return this.prescriptionDrugs;
	}

	public void setPrescriptionDrugs(Set<PrescriptionDrug> prescriptionDrugs) {
		this.prescriptionDrugs = prescriptionDrugs;
	}

	@Override
	public String toString() {
		return "Prescription [id=" + id + ", patientVisit=" + patientVisit + ", prescriptionDrugs="
				+ prescriptionDrugs + "]";
	}

}
