package com.eclinic.domain;
// Generated Jul 7, 2016 1:08:16 PM by Hibernate Tools 4.3.1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrescriptionDrug generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "prescription_drug", catalog = "eclinic")
public class PrescriptionDrug implements Serializable {

	private long id;
	private Integer qty;
	private Drug drug;
	private Prescription prescription;
	
	public PrescriptionDrug() {
	}
	
	public PrescriptionDrug(Integer qty, Drug drug, Prescription prescription) {
		this.qty = qty;
		this.drug = drug;
		this.prescription = prescription;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "drug_id", nullable = false, insertable = false, updatable = false)
	public Drug getDrug() {
		return this.drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prescription_id", nullable = false, insertable = false, updatable = false)
	public Prescription getPrescription() {
		return this.prescription;
	}

	public void setPrescription(Prescription prescription) {
		this.prescription = prescription;
	}

	@Override
	public String toString() {
		return "PrescriptionDrug [id=" + id + ", qty=" + qty + ", drug=" + drug + ", prescription=" + prescription
				+ "]";
	}

}
